import js from '@eslint/js';
import prettierPlugin from 'eslint-plugin-prettier/recommended';
import globals from 'globals';
import importPlugin from 'eslint-plugin-import';

export default [
  js.configs.recommended,
  prettierPlugin,
  {
    plugins: {
      import: importPlugin,
    },
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.jest,
        // Google Apps Script globals
        Logger: 'readonly',
        console: 'readonly',
        MailApp: 'readonly',
        GmailApp: 'readonly',
        SpreadsheetApp: 'readonly',
        ScriptApp: 'readonly',
        HtmlService: 'readonly',
        DriveApp: 'readonly',
        CacheService: 'readonly',
        ContentService: 'readonly',
        LockService: 'readonly',
        PropertiesService: 'readonly',
        Utilities: 'readonly',
        // local functions
        ANALYTICS_HEADERS: 'readonly',
        DELIVERY_MODES: 'readonly',
        OUTBOUND_HEADER_ROW: 'readonly',
        OUTBOUND_HEADERS: 'readonly',
        OUTBOUND_STATUSES: 'readonly',
        SHEET_NAMES: 'readonly',
        SIGNATURE_MODES: 'readonly',
        TEMPLATE_NAMES: 'readonly',
        buildSignatureData: 'readonly',
        appendOutboundRows: 'readonly',
        applyConfigDefaultsToPayload_: 'readonly',
        applyAnalyticsSheetTheme_: 'readonly',
        applyWorkbookPresentation_: 'readonly',
        createComposeDraft: 'readonly',
        createScheduledDraftBatch: 'readonly',
        createSelectedOutboundDraft: 'readonly',
        createSingleDraft: 'readonly',
        getAnalyticsHeaders: 'readonly',
        getConfig: 'readonly',
        getConfigDefaults: 'readonly',
        getDefaultTemplateId: 'readonly',
        getDeliveryModes: 'readonly',
        getTemplateCatalog: 'readonly',
        getSelectableTemplateNames: 'readonly',
        getSignatureModes: 'readonly',
        normalizeAndValidatePayload: 'readonly',
        isValidEmail: 'readonly',
        isValidHttpUrl: 'readonly',
        textToParagraphHtml: 'readonly',
        escapeHtml: 'readonly',
        getDispatchableOutboundPayloads: 'readonly',
        getOutboundHeaders: 'readonly',
        getOutboundSheetSnapshot_: 'readonly',
        getOutboundStatuses: 'readonly',
        getPlainTextSignature: 'readonly',
        getSheetByNameOrThrow_: 'readonly',
        getTemplateNames: 'readonly',
        resolveTemplateDefinition: 'readonly',
        renderHtmlTemplate: 'readonly',
        renderTemplateString: 'readonly',
        getSignatureHtml: 'readonly',
        getComposePayload: 'readonly',
        getSelectedOutboundPayload: 'readonly',
        getUnsentOutboundPayloads: 'readonly',
        updateOutboundRows: 'readonly',
        updateOutboundStatus: 'readonly',
        showPreviewDialog_: 'readonly',
        buildPlainTextFallback: 'readonly',
        htmlToPlainText: 'readonly',
        safeString: 'readonly',
        sendSingleEmail: 'readonly',
        logAnalyticsEvent: 'readonly',
        getAnalyticsSummary: 'readonly',
        handleSequenceNextStep: 'readonly',
        setupSheets: 'readonly',
        refreshStartHereSheet_: 'readonly',
        restyleWorkbook: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'off',
      'preserve-caught-error': 'off',
      'import/no-unresolved': 'off', // Disable for GAS as it uses global scope
    },
  },
];
